#include <iostream>
#include <random>

class RandGen
{
public:
    RandGen()
    {
        std::random_device rd;
        this->gen = std::mt19937(rd());
    }
public:
    std::mt19937 gen;
};

int main(int argc, char* argv[])
{
    RandGen rg;

    std::uniform_int_distribution<> distrib(1, 6);

    // Use distrib to transform the random unsigned int
    // generated by gen into an int in [1, 6]
    for (int n = 0; n != 10; ++n)
        std::cout << distrib(rg.gen) << ' ';
    std::cout << '\n';

    return 0;
}

