#include <iostream>
#include <random>

int main(int argc, char* argv[])
{
    std::random_device *rd = new std::random_device();  // a seed source for the random number engine
    //std::mt19937 *gen = new std::mt19937(rd()); // mersenne_twister_engine seeded with rd()
    std::mt19937 *gen = new std::mt19937((*rd)()); // mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> distrib(1, 6);

    // Use distrib to transform the random unsigned int
    // generated by gen into an int in [1, 6]
    for (int n = 0; n != 10; ++n)
        std::cout << distrib(*gen) << ' ';
    std::cout << '\n';
    delete gen;

    return 0;
}

